name: build

on:
  push:
    branches:
      - master
      - patch-1patch-1
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_REPO: ${{ secrets.KEY_REPO }}
      KEY_TOKEN: ${{ secrets.KEY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Android Keystore
        if: ${{ env.KEY_REPO != '' && env.KEY_TOKEN != '' }}
        uses: actions/checkout@v4.2.2
        with:
          repository: ${{ env.KEY_REPO }}
          token: ${{ env.KEY_TOKEN }}
          path: keystore
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.5.0
      - name: Build With Gradle
        run: |
          echo "开始编译打包"
          chmod +x gradlew
          ./gradlew :app:assembleRelease --build-cache --parallel --daemon --warning-mode all
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FQWeb
          path: ${{ github.workspace }}/app/build/outputs/apk/*/FQWeb*.apk
